several modifications made to ensure tests pass

diff --git a/backend/setup_db/test_sql_setup b/backend/setup_db/test_sql_setup
--- a/backend/setup_db/test_sql_setup
+++ b/backend/setup_db/test_sql_setup
@@ -3,20 +3,27 @@
 # To run this script
 # sudo bash sql_setup.sh
 
-# shellcheck source=/dev/null
-source .env
+env_file=$(locate ProAlx/.env)
+
+if [ -f "$env_file" ]; then
+    # shellcheck source=/dev/null
+    source "$env_file"
+else
+    echo "Error: create ProAlx/.env file"
+    exit 1
+fi
 # set env variables
 # DB_USERNAME
 # DB_PASSWORD
 
 # Create project development database
-mysql -e "CREATE DATABASE IF NOT EXISTS test_palx_db;"
+mysql -e "CREATE DATABASE IF NOT EXISTS $TEST_DB_NAME;"
 
 # Create new user with privileges
 mysql -e "CREATE USER IF NOT EXISTS '$TEST_DB_USERNAME'@'localhost' IDENTIFIED BY '$TEST_DB_PASSWORD';"
 
 # Grant privileges to the new user
-mysql -e "GRANT ALL PRIVILEGES ON test_palx_db.* TO '$TEST_DB_USERNAME'@'localhost';"
+mysql -e "GRANT ALL PRIVILEGES ON $TEST_DB_NAME.* TO '$TEST_DB_USERNAME'@'localhost';"
 
 #Allow user to observe db server performance metrics
 mysql -e "GRANT SELECT ON performance_schema.* TO '$TEST_DB_USERNAME'@'localhost';"
